import React from "react";

/**
 * ReviewOutput Component
 * Displays the AI review results with nice formatting
 */
function ReviewOutput({ review, loading, error }) {
  if (loading) {
    return (
      <div className="w-full max-w-4xl mt-6 bg-blue-50 border border-blue-200 rounded-lg p-6">
        <div className="flex items-center space-x-3">
          <div className="animate-spin rounded-full h-6 w-6 border-b-2 border-blue-600"></div>
          <div className="text-blue-700 font-medium">
            🤖 AI is reviewing your code...
          </div>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="w-full max-w-4xl mt-6 bg-red-50 border border-red-200 rounded-lg p-6">
        <div className="flex items-center space-x-3">
          <div className="text-red-600 text-xl">❌</div>
          <div>
            <div className="text-red-700 font-medium">Review Failed</div>
            <div className="text-red-600 text-sm mt-1">{error}</div>
          </div>
        </div>
      </div>
    );
  }

  if (!review) {
    return null;
  }

  return (
    <div className="w-full max-w-4xl mt-6 bg-white border border-gray-200 rounded-lg shadow-sm">
      <div className="border-b border-gray-200 px-6 py-4">
        <h2 className="text-lg font-semibold text-gray-900 flex items-center">
          <span className="text-2xl mr-2">🤖</span>
          AI Code Review Results
        </h2>
      </div>
      
      <div className="p-6">
        <div className="prose max-w-none">
          <pre className="whitespace-pre-wrap text-sm leading-relaxed text-gray-700 bg-gray-50 p-4 rounded border">
            {review}
          </pre>
        </div>
      </div>
      
      <div className="border-t border-gray-200 px-6 py-3 bg-gray-50 rounded-b-lg">
        <div className="text-xs text-gray-500">
          💡 This review was generated by AI. Please use your judgment and verify suggestions.
        </div>
      </div>
    </div>
  );
}

export default ReviewOutput; 